name: internship
description: A new Flutter application to locate all the hospitals near you.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^1.0.3
  geolocator: ^6.1.1
  provider: ^4.3.2+2
  url_launcher: ^5.7.8
  http: ^0.12.2
  flutter_rating_bar: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true